"""HTTP view serving Scheduler+ reports as a downloadable PDF.

A dedicated HTTP endpoint rather than a websocket command, since the
websocket API is JSON-only and PDF bytes don't fit that channel.
Registered once via `hass.http.register_view` from `__init__.py`'s
`async_setup` (the same one-time-per-run lifecycle as the websocket
commands - see websocket.py's own registration-timing docstring), and
reuses `report.async_build_report` so the PDF and the on-screen,
websocket-driven report (websocket.py's `generate_report` command) can
never disagree about what a report contains.
"""

from __future__ import annotations

import logging
from datetime import date

from aiohttp import web
from fpdf import FPDF
from homeassistant.components.http import KEY_HASS, HomeAssistantView

from .report import ReportData, ReportError, ReportRangeError, async_build_report

_LOGGER = logging.getLogger(__name__)

# fpdf2 column widths (mm) for the per-entity table: Time / State / Details / Source.
_COLUMN_WIDTHS = (40, 30, 70, 50)
_COLUMN_HEADERS = ("Time", "State", "Details", "Source")


class SchedulerPlusReportPdfView(HomeAssistantView):
    """Serve a report generated by report.async_build_report as a PDF download."""

    url = "/api/scheduler_plus/report/pdf"
    name = "api:scheduler_plus:report_pdf"
    # requires_auth defaults to True on HomeAssistantView: the same session
    # cookie the Lovelace card already runs under covers this request, so
    # the frontend can just navigate/fetch this URL with no extra token
    # plumbing.

    async def get(self, request: web.Request) -> web.Response:
        """Handle GET /api/scheduler_plus/report/pdf?entities=a,b&start=YYYY-MM-DD&end=YYYY-MM-DD."""
        hass = request.app[KEY_HASS]

        entity_ids = [e for e in request.query.get("entities", "").split(",") if e]
        start_param = request.query.get("start")
        end_param = request.query.get("end")

        if not entity_ids or not start_param or not end_param:
            return web.Response(
                status=400,
                text="entities, start, and end query parameters are required",
            )

        try:
            start_date = date.fromisoformat(start_param)
            end_date = date.fromisoformat(end_param)
        except ValueError:
            return web.Response(status=400, text="start/end must be YYYY-MM-DD")

        try:
            report = await async_build_report(hass, entity_ids, start_date, end_date)
        except ReportRangeError as err:
            return web.Response(status=400, text=str(err))
        except ReportError as err:
            return web.Response(status=503, text=str(err))

        pdf_bytes = await hass.async_add_executor_job(_render_pdf, report)

        filename = (
            f"scheduler-plus-report-{report.start_date.isoformat()}"
            f"-{report.end_date.isoformat()}.pdf"
        )
        return web.Response(
            body=bytes(pdf_bytes),
            content_type="application/pdf",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )


def _safe_text(value: str) -> str:
    """Best-effort latin-1 rendering for fpdf2's core (non-Unicode) fonts.

    fpdf2's built-in Helvetica font only renders latin-1 characters;
    embedding a full Unicode TTF font is out of scope for this table-only
    MVP report. A friendly name outside latin-1 (e.g. Hebrew, common in
    this integration's own userbase given its YidCal-based day conditions/
    time providers) renders with '?' substitutions instead of failing PDF
    generation entirely.
    """
    return value.encode("latin-1", "replace").decode("latin-1")


def _render_pdf(report: ReportData) -> bytearray:
    """Render a ReportData as a simple table-per-entity PDF.

    Synchronous - fpdf2 has no async API - so this always runs via
    hass.async_add_executor_job, never directly on the event loop. Table-
    only for this pass (no embedded chart); the same compacted ReportPoint
    list the on-screen report renders, so row count is already bounded by
    report.py's per-entity compaction/truncation.
    """
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(
        0,
        10,
        _safe_text(
            f"Scheduler+ Report: {report.start_date.isoformat()} "
            f"to {report.end_date.isoformat()}"
        ),
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(4)

    for entity in report.entities:
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(
            0,
            8,
            _safe_text(f"{entity.friendly_name} ({entity.entity_id})"),
            new_x="LMARGIN",
            new_y="NEXT",
        )

        if entity.no_data:
            pdf.set_font("Helvetica", "I", 10)
            pdf.cell(
                0,
                6,
                "No data found - may be outside your Home Assistant history retention.",
                new_x="LMARGIN",
                new_y="NEXT",
            )
            pdf.ln(4)
            continue

        pdf.set_font("Helvetica", "B", 9)
        for width, header in zip(_COLUMN_WIDTHS, _COLUMN_HEADERS):
            pdf.cell(width, 6, header, border=1)
        pdf.ln(6)

        pdf.set_font("Helvetica", "", 9)
        for point in entity.points:
            details = ", ".join(
                f"{key}={value}"
                for key, value in point.attributes.items()
                if value is not None
            )
            source = (
                f"Rule: {point.rule_name} ({point.schedule_name})"
                if point.source == "rule"
                else "Other"
            )
            row = (
                point.at.strftime("%Y-%m-%d %H:%M:%S"),
                point.state,
                details,
                source,
            )
            for width, cell_value in zip(_COLUMN_WIDTHS, row):
                pdf.cell(width, 6, _safe_text(str(cell_value))[:60], border=1)
            pdf.ln(6)

        if entity.truncated:
            pdf.set_font("Helvetica", "I", 8)
            pdf.cell(
                0,
                6,
                "Report truncated - too many changes in this range to list all of them.",
                new_x="LMARGIN",
                new_y="NEXT",
            )

        pdf.ln(4)

    return pdf.output()
