"""HTTP view serving Scheduler+ reports as a downloadable PDF.

A dedicated HTTP endpoint rather than a websocket command, since the
websocket API is JSON-only and PDF bytes don't fit that channel.
Registered once via `hass.http.register_view` from `__init__.py`'s
`async_setup` (the same one-time-per-run lifecycle as the websocket
commands - see websocket.py's own registration-timing docstring), and
reuses `report.async_build_report` so the PDF and the on-screen,
websocket-driven report (websocket.py's `generate_report` command) can
never disagree about what a report contains.
"""

from __future__ import annotations

import logging
from collections.abc import Callable
from datetime import date, datetime
from typing import Any

from aiohttp import web
from fpdf import FPDF
from homeassistant.components.http import KEY_HASS, HomeAssistantView

from .report import (
    ReportData,
    ReportError,
    ReportPoint,
    ReportRangeError,
    async_build_report,
)

_LOGGER = logging.getLogger(__name__)

# fpdf2 column widths (mm), landscape A4 (297mm) minus 16mm margins each side.
_COLUMN_WIDTHS = (40, 28, 118, 79)
_COLUMN_HEADERS = ("Time", "State", "Details", "Source")

# Color palette (RGB 0-255) - a single small set reused throughout, rather
# than picking colors ad hoc per element, so the PDF reads as one design
# instead of a patchwork. Body text is always _TEXT_DARK/_TEXT_MUTED against
# a plain white/near-white row background - state/source get their meaning
# from *text* color, not a colored cell fill, specifically to avoid the bug
# this redesign fixes (a fill color with no matching text-color reset made
# an earlier version's row text invisible - white-on-white/light).
_ACCENT = (14, 148, 190)
_TEXT_DARK = (30, 41, 59)
_TEXT_MUTED = (110, 118, 128)
_HEADER_BG = (30, 41, 59)
_HEADER_TEXT = (255, 255, 255)
_ROW_ALT_BG = (246, 248, 250)
_ROW_BORDER = (224, 228, 232)
_STATE_ACTIVE = (13, 130, 90)  # on/heat/cool/open/playing
_STATE_INACTIVE = (120, 128, 138)  # off/idle/closed
_STATE_OTHER = (178, 110, 15)  # unavailable/unknown/anything else
_SOURCE_RULE = (14, 116, 190)
_SOURCE_OTHER = (140, 148, 158)

_ACTIVE_STATES = {"on", "open", "playing", "heat", "cool", "heat_cool", "auto", "dry", "fan_only"}
_INACTIVE_STATES = {"off", "closed", "idle"}


def _state_color(state: str) -> tuple[int, int, int]:
    """Which text color communicates a state's meaning at a glance."""
    lowered = state.lower()
    if lowered in _ACTIVE_STATES:
        return _STATE_ACTIVE
    if lowered in _INACTIVE_STATES:
        return _STATE_INACTIVE
    return _STATE_OTHER


class _ReportPdf(FPDF):
    """FPDF subclass adding a page-number footer to every page automatically.

    fpdf2 calls footer() once per page on its own; this is the idiomatic way
    to get consistent page chrome without re-invoking it manually per
    add_page() call (the previous version's footer only ever appeared once,
    at the very end, regardless of how many pages the report spanned).
    """

    def footer(self) -> None:
        """Draw a small centered page-number line near the bottom margin."""
        self.set_y(-12)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*_TEXT_MUTED)
        self.cell(0, 8, f"Scheduler+  ·  Page {self.page_no()}", align="C")


class SchedulerPlusReportPdfView(HomeAssistantView):
    """Serve a report generated by report.async_build_report as a PDF download."""

    url = "/api/scheduler_plus/report/pdf"
    name = "api:scheduler_plus:report_pdf"
    # requires_auth defaults to True on HomeAssistantView. A plain same-tab
    # navigation/fetch to this URL is NOT enough on its own, despite the
    # browser holding a valid HA session - the frontend (report-dialog.ts's
    # _downloadPdf) explicitly sends the signed-in user's hass.auth access
    # token as a Bearer header, the same way the rest of Home Assistant's
    # own frontend authenticates its /api/* calls.

    async def get(self, request: web.Request) -> web.Response:
        """Handle GET /api/scheduler_plus/report/pdf?entities=a,b&start=YYYY-MM-DD&end=YYYY-MM-DD."""
        hass = request.app[KEY_HASS]

        entity_ids = [e for e in request.query.get("entities", "").split(",") if e]
        start_param = request.query.get("start")
        end_param = request.query.get("end")

        if not entity_ids or not start_param or not end_param:
            return web.Response(
                status=400,
                text="entities, start, and end query parameters are required",
            )

        try:
            start_date = date.fromisoformat(start_param)
            end_date = date.fromisoformat(end_param)
        except ValueError:
            return web.Response(status=400, text="start/end must be YYYY-MM-DD")

        try:
            report = await async_build_report(hass, entity_ids, start_date, end_date)
        except ReportRangeError as err:
            return web.Response(status=400, text=str(err))
        except ReportError as err:
            return web.Response(status=503, text=str(err))

        pdf_bytes = await hass.async_add_executor_job(_render_pdf, report)

        filename = (
            f"scheduler-plus-report-{report.start_date.isoformat()}"
            f"-{report.end_date.isoformat()}.pdf"
        )
        return web.Response(
            body=bytes(pdf_bytes),
            content_type="application/pdf",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )


def _safe_text(value: str) -> str:
    """Best-effort latin-1 rendering for fpdf2's core (non-Unicode) fonts.

    fpdf2's built-in Helvetica font only renders latin-1 characters;
    embedding a full Unicode TTF font is out of scope for this table-only
    MVP report. A friendly name outside latin-1 (e.g. Hebrew, common in
    this integration's own userbase given its YidCal-based day conditions/
    time providers) renders with '?' substitutions instead of failing PDF
    generation entirely.
    """
    return value.encode("latin-1", "replace").decode("latin-1")


def _line_count(pdf: FPDF, value: str, width: float) -> int:
    """Estimate wrapped lines so adjacent table rows never overlap."""
    lines = 1
    current = ""
    for word in _safe_text(value).split():
        candidate = f"{current} {word}".strip()
        if current and pdf.get_string_width(candidate) > width - 4:
            lines += 1
            current = word
        else:
            current = candidate
    return lines


def _humanize_word(value: str) -> str:
    """"cool" -> "Cool", "hvac_action" values like "heating" -> "Heating"."""
    spaced = value.replace("_", " ")
    return spaced[:1].upper() + spaced[1:] if spaced else spaced


def _format_temp(value: float) -> str:
    return f"{round(value, 1)}°"


def _format_pdf_time(at: datetime) -> str:
    """e.g. "Aug 24, 2026  3:05 PM" - no leading zeros, without relying on

    %-d/%-I: those "no leading zero" strftime flags are a glibc extension
    (Windows' C runtime raises ValueError for them), so day/hour are built
    from plain ints instead of leaning on a platform-specific format flag.
    """
    hour12 = at.hour % 12 or 12
    return f"{at:%b} {at.day}, {at.year}  {hour12}:{at:%M %p}"


def _describe_attributes(domain: str, point: ReportPoint) -> str:
    """A domain-aware, human-readable summary of a point's tracked attributes.

    Mirrors frontend/src/report-dialog.ts's describeAttributes exactly, so
    the PDF and the on-screen report never disagree about what a row means -
    see this module's own docstring for why the two must stay in sync. Raw
    "current_temperature=70, temperature=69" key=value text (the original
    version of this column) meant nothing to someone just reading the
    report; light's brightness=200 is even less legible without converting
    HA's raw 0-255 scale to a percentage.
    """
    if domain == "climate":
        parts: list[str] = []
        target = point.attributes.get("temperature")
        current = point.attributes.get("current_temperature")
        action = point.attributes.get("hvac_action")
        if isinstance(target, (int, float)):
            parts.append(f"Target {_format_temp(target)}")
        if isinstance(current, (int, float)):
            parts.append(f"Room {_format_temp(current)}")
        if isinstance(action, str) and action:
            parts.append(_humanize_word(action))
        return " · ".join(parts)
    if domain == "light":
        brightness = point.attributes.get("brightness")
        if isinstance(brightness, (int, float)):
            return f"Brightness {round(brightness / 255 * 100)}%"
        return ""
    return ""


# Per domain, which of a point's tracked attributes count as a "real" change
# worth its own PDF row - as opposed to routine sensor noise (climate's
# current_temperature drifting by a degree every few minutes) that's only
# useful as a continuous line in the on-screen chart, not as a wall of
# near-identical rows. Mirrors frontend/src/report-dialog.ts's
# LIST_SIGNIFICANT_KEYS - see that constant's docstring for the full
# reasoning. Nothing is filtered for light/switch: their only tracked
# signal already is the meaningful thing.
_LIST_SIGNIFICANT_KEY: dict[str, Callable[[ReportPoint], Any]] = {
    "climate": lambda point: (
        point.state,
        point.attributes.get("temperature"),
        point.attributes.get("hvac_action"),
    ),
}


def _significant_points(points: list[ReportPoint], domain: str) -> list[ReportPoint]:
    """Collapse `points` to just the ones significant enough for a PDF row."""
    key_of = _LIST_SIGNIFICANT_KEY.get(domain)
    if key_of is None:
        return points
    kept: list[ReportPoint] = []
    last_key: Any = None
    for point in points:
        key = key_of(point)
        if not kept or key != last_key:
            kept.append(point)
            last_key = key
    return kept


def _draw_table_header(pdf: FPDF) -> None:
    """Draw the dark column-header row at the current position."""
    pdf.set_fill_color(*_HEADER_BG)
    pdf.set_text_color(*_HEADER_TEXT)
    pdf.set_font("Helvetica", "B", 8.5)
    for width, header in zip(_COLUMN_WIDTHS, _COLUMN_HEADERS):
        pdf.cell(width, 7.5, header.upper(), fill=True)
    pdf.ln(7.5)


def _render_pdf(report: ReportData) -> bytearray:
    """Render a clean, readable landscape PDF: hairline row separators and
    color-coded text (not colored cell fills - see this module's palette
    comment for why) rather than a busy full grid, one small header/footer
    per page, and a compact title block up front.
    """
    pdf = _ReportPdf(orientation="L", format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.set_margins(16, 16, 16)
    pdf.add_page()

    pdf.set_text_color(*_TEXT_DARK)
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 10, "Scheduler+ Report", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(*_TEXT_MUTED)
    pdf.set_font("Helvetica", "", 10.5)
    date_range = (
        report.start_date.isoformat()
        if report.start_date == report.end_date
        else f"{report.start_date.isoformat()} to {report.end_date.isoformat()}"
    )
    pdf.cell(0, 6, date_range, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.set_draw_color(*_ACCENT)
    pdf.set_line_width(0.8)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(7)

    total_width = sum(_COLUMN_WIDTHS)
    for entity_index, entity in enumerate(report.entities):
        if entity_index > 0:
            pdf.ln(7)

        pdf.set_text_color(*_TEXT_DARK)
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 7, _safe_text(entity.friendly_name), new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*_TEXT_MUTED)
        pdf.set_font("Helvetica", "", 8.5)
        pdf.cell(0, 5, entity.entity_id, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

        if entity.no_data:
            pdf.set_text_color(*_TEXT_MUTED)
            pdf.set_font("Helvetica", "I", 9)
            pdf.cell(0, 6, "No data found - may be outside your Home Assistant history retention.",
                     new_x="LMARGIN", new_y="NEXT")
            continue

        _draw_table_header(pdf)

        rows = _significant_points(entity.points, entity.domain)
        for index, point in enumerate(rows):
            details = _describe_attributes(entity.domain, point)
            source_text = point.rule_name if point.source == "rule" else "Other"
            values = (
                _format_pdf_time(point.at),
                _humanize_word(point.state),
                details,
                source_text or "",
            )
            row_height = max(
                _line_count(pdf, str(value), width)
                for value, width in zip(values, _COLUMN_WIDTHS)
            ) * 5 + 2

            if pdf.get_y() + row_height > pdf.page_break_trigger:
                pdf.add_page()
                _draw_table_header(pdf)

            x, y = pdf.get_x(), pdf.get_y()
            if index % 2 == 1:
                pdf.set_fill_color(*_ROW_ALT_BG)
                pdf.rect(x, y, total_width, row_height, style="F")

            for column, (width, value) in enumerate(zip(_COLUMN_WIDTHS, values)):
                pdf.set_xy(x, y + 1.2)
                if column == 1:
                    pdf.set_text_color(*_state_color(point.state))
                    pdf.set_font("Helvetica", "B", 8.5)
                elif column == 3:
                    pdf.set_text_color(*(_SOURCE_RULE if point.source == "rule" else _SOURCE_OTHER))
                    pdf.set_font("Helvetica", "", 8.5)
                else:
                    pdf.set_text_color(*_TEXT_DARK)
                    pdf.set_font("Helvetica", "", 8.5)
                pdf.multi_cell(width, 5, _safe_text(str(value)), border=0, align="L")
                x += width

            pdf.set_draw_color(*_ROW_BORDER)
            pdf.set_line_width(0.2)
            pdf.line(pdf.l_margin, y + row_height, pdf.l_margin + total_width, y + row_height)
            pdf.set_xy(pdf.l_margin, y + row_height)

        if entity.truncated:
            pdf.ln(1)
            pdf.set_text_color(*_TEXT_MUTED)
            pdf.set_font("Helvetica", "I", 8)
            pdf.cell(0, 6, "Truncated - too many changes in this range to list all of them.",
                     new_x="LMARGIN", new_y="NEXT")

    return pdf.output()
