set_mode:
  fields:
    mode:
      required: true
      example: No school
      selector:
        text:
    state:
      required: true
      default: "on"
      selector:
        select:
          options:
            - label: "On"
              value: "on"
            - label: "Off"
              value: "off"
            - label: "Follow the weekly repeat"
              value: auto
    date:
      required: false
      example: "2026-09-25"
      selector:
        date:
